### ISSUE TITLE
WindowOverflow and ESP_CORE_DUMP Error

### ISSUE THREAD

**Issue by fjalonzo** [espressif/esp-mdf#22]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1]
- Core (if using chip or module): [ESP-WROOM32]
- MDF version (``git rev-parse --short HEAD`` to get the commit id.): f028311
    //bd6ea4393c7d2f059fc4decc70f1ec3eb3597268
- Development Env:		[VS Code]
- Operating System:		[Windows]
- Power Supply:         [USB]

## Problem Description

0x40080000: _WindowOverflow4 at C:/msys32/home/FrancisJeralyn/esp/esp-mdf/esp-idf/components/freertos/xtensa_vectors.S:1685

0x4008c4ac: coex_bt_high_prio at /home/qgu/git_tree/chip7.1_rtc/board_code/app_test/pp/rtc/bt_bb.c:402

E (254) esp_core_dump: Failed to mmap core dump data `(260)!`

![capture1](https://user-images.githubusercontent.com/44130966/52178418-3aedf200-2809-11e9-916b-454ce3130a21.PNG)

![capture2](https://user-images.githubusercontent.com/44130966/52178349-4bea3380-2808-11e9-9f4e-24b0d17163ad.PNG)

This is the "**get_started**" example program.

**Comment by igrr** [comment]
FWIW, `WindowOverflow` and similar lines are not an error: IDF monitor decodes addresses found in serial output, converting them to function names. See https://docs.espressif.com/projects/esp-idf/en/latest/get-started/idf-monitor.html#automatically-decoding-addresses.
With regards to the error coming from core dump — it is benign, no real issue, but should indeed be fixed in IDF.

**Comment by ESP-LBB** [comment]
Closing as this question appears to be answered.
