### ISSUE TITLE
ESP-MDF Mupgrade procedure question

### ISSUE THREAD

**Issue by sw-dev-code** [espressif/esp-mdf#239]
I'm doing the testing of the ESP-MESH network and I'm interested in what will happen in a case when Mupgrade process is started but one of the nodes is connected to the MESH network but not in a range of a ROOT device?

**Comment by esp-lqq** [comment]
1. You can refer to the code during the upgrade process.
2. The device upgrade is divided into two steps. The root node downloads the firmware and synchronizes it in the firmware network.
After the firmware download is complete, the mac addresses of all devices in the network that need to be upgraded will be obtained. If the device has joined the network at this time, it can be upgraded by the way, otherwise it cannot be upgraded.

**Comment by sw-dev-code** [comment]
Great, for me the most important thing is that edge nodes (not connected to root) is going to be updated.

Thank you for the help.
